### ISSUE TITLE
missing method in interface

### ISSUE THREAD

**Issue by Hacksore** [to2mbn/skinview3d#16]
When using the module from npm I ran into the .add method not being found on IAnimation. Although this is not breaking anything in the codebase I do receive typescript errors as the method can't be found.

![Issue](https://i.imgur.com/VdZuv8E.png)

```typescript
export interface IAnimation {
	play(player: PlayerObject, time: number): void;

	// this defintion is missing or is not being inherited correctly 
	add(animation: AnimationFn): AnimationHandle; 
}
```
https://github.com/to2mbn/skinview3d/blob/master/types/animation.d.ts#L4

Let me know what the issue is here or if I'm doing something wrong. For now I've manually edited the typings file but obviously, that is a hacky workaround.

**Comment by g-plane** [comment]
Can you let me know what you constructed in `this.skinViewer.animation = new skinvie...`?

**Comment by Hacksore** [comment]
@g-plane I have this.

``` typescript
this.skinViewer.animation = new skinview3d.CompositeAnimation();
```

**Comment by g-plane** [comment]
It is really a problem. However, adding `add` method to `IAnimation` may not be a good solution.

**Comment by g-plane** [comment]
Temporary solution:
![image](https://user-images.githubusercontent.com/17216317/36708813-e2bd4132-1baf-11e8-9de3-9c8e245a6660.png)

**Comment by Hacksore** [comment]
@g-plane Alright I'll try this when I get home today. Any idea on what the permanent solution to the problem is?

**Comment by g-plane** [comment]
It seems it is hard to solve this problem by modifying type declarations files.

For example, in TypeScript:
We declare a variable whose type is `Node`, and as we know `HTMLElement` inherits from `Node`.
![image](https://user-images.githubusercontent.com/17216317/36767456-8602f394-1c75-11e8-8bda-c270d0bd73bc.png)

No compile errors here. However, TypeScript still regards `something` is `Node`:
![image](https://user-images.githubusercontent.com/17216317/36767589-19383502-1c76-11e8-888b-b4a2a55dfb54.png)

Now if we call some methods on `HTMLElement`, TS will throws:
![image](https://user-images.githubusercontent.com/17216317/36767656-6703f852-1c76-11e8-9d9c-04659379b965.png)
So we can use type assertion:
![image](https://user-images.githubusercontent.com/17216317/36768008-fae37790-1c77-11e8-9f96-a9acc2e23eca.png)
(You can ignore the `void` keyword.)

**Comment by yushijinhun** [comment]
I don't think it's a problem.

The type of property `SkinViewer.animation` is `Animation`. According to [Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle), as `CompositeAnimation` is a subtype of `Animation`, you can set `SkinViewer.animation` to it directly.

But when you obtain the value of `SkinViewer.animation`, what you get is definitely an `Animation` but possibly not a `CompositeAnimation`, even though you have set it to a `CompositeAnimation` before (at least the type system thinks so). If you think you are right and it must be a `CompositeAnimation`, you should use explicit type conversion.

**Comment by Hacksore** [comment]
I think this is solely a bug with the typings file and the npm module. As of now, I have the skinview3d src in my angular project and I no longer receive the missing method error.

![screenshot](https://i.imgur.com/hMDtBkL.png)

**Comment by g-plane** [comment]
@Hacksore I have let TypeScript compiler to generate typings files. TypeScript still throw error. In other words, the typings files should be OK.

**Comment by Hacksore** [comment]
@g-plane I'd say we can close this issue then.

**Comment by yushijinhun** [comment]
Note that this issue was solved in https://github.com/bs-community/skinview3d/commit/127d2ee7a387782eb935c54ad4489b7019fcea78.
