### ISSUE TITLE
crossOrigin = ""

### ISSUE THREAD

**Issue by Hacksore** [to2mbn/skinview3d#17]
Any reason for this?
```typescript
this.skinImg.crossOrigin = "";
```
https://github.com/to2mbn/skinview3d/blob/master/src/viewer.js#L97

**Comment by yushijinhun** [comment]
This comes from [earthiverse's original code](https://github.com/earthiverse/3D-Minecraft-Skin-Viewer/blob/master/index.html#L171). I don't know the reason either.

**Comment by Hacksore** [comment]
@yushijinhun I think we change it to the following for CORS requests.

```
this.skinImg.crossOrigin = "Anonymous";
```
