### ISSUE TITLE
Original cape dimensions won't load (22x17)

### ISSUE THREAD

**Issue by Hacksore** [to2mbn/skinview3d#4]
Seems like only the new style capes are loading (64x32).  There are some needs to load a cape from Mojang where the cape size will not be converted to the new dimensions. Could we have maybe a config flag to ignore cape aspect ratio?

https://github.com/to2mbn/skinview3d/blob/master/src/viewer.js#L135``

**Comment by yushijinhun** [comment]
The cape aspect ratio cannot be ignored, as I'm using relative positions to bind textures. So I just copy the old cape (22x17) to a new canvas (64x32).
